name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  tests:

    runs-on: ubuntu-latest

    env:
      DATABASE_URL: mysql://root:root@127.0.0.1/coop_tilleuls_sylius_click_n_collect_plugin_%kernel.environment%?serverVersion=8.0

    steps:
      - uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install Symfony Flex
        run: |
          composer global config --no-plugins allow-plugins.symfony/flex true
          composer global require --no-progress --no-scripts --no-plugins "symfony/flex:^1.10"

      - name: Install dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

      - name: Configure test app
        run: |
          sudo /etc/init.d/mysql start
          (cd tests/Application && bin/console doctrine:database:create -e panther)
          (cd tests/Application && bin/console doctrine:schema:create -e panther)
          (cd tests/Application && bin/console sylius:fixtures:load -e panther --no-interaction)

          (cd tests/Application && yarn install)
          (cd tests/Application && yarn build)
          (cd tests/Application && bin/console assets:install public -e panther)

      - name: Run test suite
        run: vendor/bin/phpunit

  php-cs-fixer:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: PHP-CS-Fixer
        uses: docker://oskarstark/php-cs-fixer-ga
